### ISSUE TITLE
Prefetch Next Track

### ISSUE THREAD

**Issue by krak3n** [thisissoon/FM-SoundWave#3]
Whilst the current track is playing we should pre-fetch the next track.

**Comment by jamesjwarren** [comment]
@krak3n does this mean the player could support gapless playback? i.e. from one track to the next with no discernible break. Or would that be more tricky?

**Comment by krak3n** [comment]
@jamesjwarren there would still be a gap between the playing track ending and polling redis for the next item, but the max delay **should** be 1 second. We could lower the polling down to 500ms or 200ms etc.

Tbh i'm not really happy with SoundWave polling redis for the next track and Im sure there is some better logic we could use to try and get the delay down.

**Comment by krak3n** [comment]
This was merged in #7 

However thinking about it we could also Prefetch on the `add` event from the API as well so I'll get another PR in for that.
